# Generated by Django 3.2.12 on 2023-07-21 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapi', '0002_blacklistedtoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blacklistedtoken',
            name='token',
            field=models.TextField(),
        ),
    ]
