env:
  - key: DJANGO_SETTINGS_MODULE
    value: "core.settings"

build:
  - command: python manage.py collectstatic --noinput
  - command: python manage.py migrate --noinput

services:
  - name: django-app
    buildCommand: pip install -r requirements.txt
    env:
      - key: ALLOWED_HOSTS
        value: "https://marketsmind-be.onrender.com"
    startCommand: gunicorn core.wsgi:application
      # Add any other environment variables your app needs
